######
###### jwt
######
jwt:
  secret-key: demokey
  expiration: 1    # 1일
  refresh-expiration: 14    # 14일(2주)
  issuer: demo!@1232
  #  token-validity-in-seconds: 600 # 10 min

---
spring:
  config:
    activate:
      on-profile: member-local


---
spring:
  config:
    activate:
      on-profile: member-dev


---
spring:
  config:
    activate:
      on-profile: member-prod

