spring:
  pid:
    file: pid-batch-demo.pid
  profiles:
    active: local
    group:
      local:
        - local
        - member-local
        - db-local
        - quartz-local
      dev:
        - dev
        - member-dev
        - db-dev
        - quartz-prod
      prod:
        - prod
        - member-prod
        - db-prod
        - quartz-prod
    include:
      - member
      - db
      - quartz
  #  devtools:
  #    livereload:
  #      enabled: true

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

---
spring:
  config:
    activate:
      on-profile: local

server:
  port: 9094

---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 9094

---
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 9094
