spring:
  cloud:
    aws:
      credentials:
        access-key: demo-access-key
        secret-key: demo-secret-key
        #      profile-name: stratospheric
      region:
        static: ap-northeast-2
        auto: false
      bucket:
        static: demo-bucket-static
      #    region: ap-northeast-2
      #    accessKeyId: demo-accessKeyId
      #    secretKey: demo-secretKey

---
spring:
  config:
    activate:
      on-profile: aws-local


---
spring:
  config:
    activate:
      on-profile: aws-dev


---
spring:
  config:
    activate:
      on-profile: aws-prod

